-- MySQL Script generated by MySQL Workbench
-- Ср 12 дек 2018 03:31:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SPbSU_log_analysis_system
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SPbSU_log_analysis_system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SPbSU_log_analysis_system` ;
USE `SPbSU_log_analysis_system` ;

-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Users` (
  `id` INT NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = FEDERATED;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Courses` (
  `id` INT NOT NULL,
  `title` VARCHAR(30) NOT NULL,
  `russian_title` VARCHAR(25) NULL,
  `hash` VARCHAR(50) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_Courses_Users_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Courses_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Logs` (
  `id` INT NOT NULL,
  `load_date` DATE NOT NULL,
  `course_id` INT NOT NULL,
  PRIMARY KEY (`id`, `course_id`),
  INDEX `fk_Logs_Courses1_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `fk_Logs_Courses1`
    FOREIGN KEY (`course_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Courses` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Modules` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `hash` VARCHAR(50) NOT NULL,
  `log_id` INT NOT NULL,
  PRIMARY KEY (`id`, `log_id`),
  INDEX `fk_Modules_Logs1_idx` (`log_id` ASC) VISIBLE,
  CONSTRAINT `fk_Modules_Logs1`
    FOREIGN KEY (`log_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Logs` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Lessons` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `hash` VARCHAR(50) NOT NULL,
  `link` VARCHAR(120) NOT NULL,
  `module_id` INT NOT NULL,
  PRIMARY KEY (`id`, `module_id`),
  INDEX `fk_Lessons_Modules1_idx` (`module_id` ASC) VISIBLE,
  CONSTRAINT `fk_Lessons_Modules1`
    FOREIGN KEY (`module_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Modules` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Videos` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `chart_link` VARCHAR(120) NOT NULL,
  `materials_viewed` FLOAT NOT NULL,
  `users_watched` FLOAT NOT NULL,
  `is_most_viewed` TINYINT NULL,
  `link` VARCHAR(120) NOT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`id`, `lesson_id`),
  INDEX `fk_Videos_Lessons1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_Videos_Lessons1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Lessons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Tests` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `hash` VARCHAR(50) NOT NULL,
  `lesson_id` INT NOT NULL,
  PRIMARY KEY (`id`, `lesson_id`),
  INDEX `fk_Tests_Lessons1_idx` (`lesson_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tests_Lessons1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Lessons` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Attempts` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `average_grade` FLOAT NOT NULL,
  `median_grade` FLOAT NOT NULL,
  `max_grade` FLOAT NOT NULL,
  `number_of_solutions` INT NOT NULL,
  `test_id` INT NOT NULL,
  PRIMARY KEY (`id`, `test_id`),
  INDEX `fk_Attempts_Tests1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_Attempts_Tests1`
    FOREIGN KEY (`test_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Tests` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SPbSU_log_analysis_system`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SPbSU_log_analysis_system`.`Questions` (
  `id` INT NOT NULL,
  `number` INT NOT NULL,
  `right_answers_percent` FLOAT NOT NULL,
  `attempt_id` INT NOT NULL,
  PRIMARY KEY (`id`, `attempt_id`),
  INDEX `fk_Questions_Attempts1_idx` (`attempt_id` ASC) VISIBLE,
  CONSTRAINT `fk_Questions_Attempts1`
    FOREIGN KEY (`attempt_id`)
    REFERENCES `SPbSU_log_analysis_system`.`Attempts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
